@extends('layouts.dashboard')

@section('content')
<div class="p-6 space-y-6">

    <!-- PAGE HEADER -->
    <div class="flex items-center justify-between no-print">
        <div>
            <h1 class="text-3xl font-extrabold text-[#3E3F29] tracking-tight">
                Income per Coordinator
            </h1>
            <p class="text-sm text-gray-600 mt-1">
                Total income generated by each coordinator
            </p>
        </div>


        <div class="flex items-center gap-3">
            <a href="{{ route('dashboard') }}"
               class="px-4 py-2 text-sm rounded-lg
                      border border-[#A1BC98]
                      text-[#3E3F29]
                      hover:bg-[#E3EAD7] transition">
                ← Back
            </a>

            <button onclick="window.print()" 
                    class="px-4 py-2 text-sm rounded-lg
                           bg-[#3E3F29] text-white
                           hover:bg-[#2c2d1f] transition">
                🖨️ Print
            </button>
        </div>
    </div>

    <!-- ================= TABLE CARD ================= -->
    <div class="bg-white rounded-2xl shadow-sm overflow-hidden print:shadow-none">

        <table class="w-full text-sm text-left">
            <thead class="bg-[#A1BC98]/40 text-[#3E3F29]">
                <tr>
                    <th class="py-3 px-5 font-semibold">#</th>
                    <th class="py-3 px-5 font-semibold">Coordinator</th>
                    <th class="py-3 px-5 font-semibold">Total Bookings</th>
                    <th class="py-3 px-5 font-semibold">Total Income</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-[#778873]/20">
                @php
                    $incomes = [
                        ['1','Juan Dela Cruz','28','₱140,000'],
                        ['2','April Martinez','25','₱125,000'],
                        ['3','Mark Kevin','23','₱115,000'],
                        ['4','Lara Santos','21','₱105,000'],
                        ['5','Ryan Torres','19','₱95,000'],
                        ['6','Carla Perez','18','₱90,000'],
                        ['7','Joshua Nunez','16','₱80,000'],
                        ['8','Maria Bello','15','₱75,000'],
                        ['9','Alex Lim','14','₱70,000'],
                        ['10','Anna Reyes','12','₱60,000'],
                    ];
                @endphp

                @foreach($incomes as [$id, $coordinator, $bookings, $income])
                <tr class="hover:bg-[#A1BC98]/20 transition print:hover:bg-transparent">
                    <td class="py-3 px-5 font-bold text-[#3E3F29]">{{ $id }}</td>
                    <td class="py-3 px-5 text-[#3E3F29]">{{ $coordinator }}</td>
                    <td class="py-3 px-5 font-bold text-[#3E3F29]">{{ $bookings }}</td>
                    <td class="py-3 px-5 font-semibold text-[#3E3F29]">{{ $income }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

    </div>

</div>

<!-- ================= PRINT RULES ================= -->
<style>
@media print {

    .no-print {
        display: none !important;
    }

    body * {
        background: white !important;
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        border: 1px solid #A1BC98 !important;
        padding: 12px 20px !important;
    }

    th {
        background: #A1BC98 !important;
        color: #3E3F29 !important;
        font-weight: 600 !important;
    }
}
</style>
@endsection
